project_identifier: testseptember
api_key: 3037dd837eb2cd0f6a9b04438eceabfa
preserve_hierarchy: true
files:
  - source: /*.properties
    translation: /translations/%locale%/%original_file_name%
    "two_letters_code" : 
    "de" : "german",
   "fr" : "fr-frr"
  
