files:
  - source: '*.xml'
    ignore:
      - es/strings (1).xml
      - uk/strings (1).xml
    translation: /%locale_with_underscore%/%original_file_name%
    languages_mapping:
      language:
        ru-UA: eu-UA
    content_segmentation: '0'
    translatable_elements:
      - </post_title><post_content>
